# Generated by Django 3.1.1 on 2022-01-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_auto_20220117_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_data',
            name='value2',
            field=models.FloatField(blank=True, default=20),
            preserve_default=False,
        ),
    ]
